name: Deploy
on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set repo name
        id: repo
        run: |
         echo "::set-output name=repo::$(echo ${{ github.repository }} | cut -d'/' -f2)"

      - name: Set container name
        id: container
        run: |
          if [[ "${{ github.workflow }}" == "Land" ]]; then
            echo "::set-output name=container::$(echo ${{ steps.repo.outputs.repo }} | cut -d'/' -f2 | tr '.' '-')-land"
          else
            echo "::set-output name=container::$(echo ${{ steps.repo.outputs.repo }} | cut -d'/' -f2 | tr '.' '-')"
          fi

      - name: Set image tag
        id: tag
        run: |
          if [[ "${{ github.workflow  }}" == "Land" ]]; then
            echo "::set-output name=tag::land"
          elif [[ "${{ github.workflow }}" == "Deploy" ]]; then
            echo "::set-output name=tag::latest"
          else
            echo "Invalid deployTo value"
            exit 1
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Print Names
        run: |
          echo "Repo: ${{ steps.repo.outputs.repo }}"
          echo "Container: ${{ steps.container.outputs.container }}"
          echo "Tag: ${{ steps.tag.outputs.tag }}"  

      - name: Log in to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        uses: docker/login-action@v1
        with:
          username: canmingir
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: canmingir/${{ steps.repo.outputs.repo }}:${{ steps.tag.outputs.tag }}
          context: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v2
        with:
          registryUsername: canmingir
          registryUrl: registry.hub.docker.com
          registryPassword: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          containerAppName: ${{ steps.container.outputs.container }}
          resourceGroup: NucGroup
          imageToDeploy: registry.hub.docker.com/canmingir/${{ steps.repo.outputs.repo }}:${{ steps.tag.outputs.tag }}

