name: React Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Eslint
        run: npm i eslint

      - name: Run Lint
        run: npm run lint

        